'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.261
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Scoreboard.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property buzzer() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("buzzer", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property g_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_all_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_all_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property g_all_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("g_all_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_all_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_all_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_all_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_all_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_decimal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_decimal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_dots_off() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_dots_off", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property r_dots_on() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("r_dots_on", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property scoreboard() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scoreboard", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
